### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by francesco-sparascio** [awesome-yasin/PDF-Verse#25]
I followed all the steps to install the program, but when I run the command "npm start", an error occurs.

This is the error:
npm ERR! Missing script: "start"
npm ERR! 
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in: C:\Users\franc\AppData\Local\npm-cache\_logs\2023-10-01T14_04_50_585Z-debug-0.log

**Comment by KarthikHebbarMN** [comment]
Thats because there is no "start" script defined. 
Switch to "main" branch and run
